### ISSUE TITLE
Memory Issue (High Priority)

### ISSUE THREAD

**Issue by J-Talon** [CammHd/Bedwars#29]
The way that we register blocks in the game is taking up too much memory. 
Find a way to reduce the memory.

**Comment by J-Talon** [comment]
I'm currently thinking about tags of 1 byte at most for all 8 possible teams on the game. 
    We'll use this tag to reduce usage from 2.8 GB to possibly less than 300 MB hopefully.

**Comment by MisterXIII** [comment]
TODO: 
Stop using built in metadata system. Key would be hash of coordinates, value would be a byte.
At the beginning, only register generator blocks, beds, and chests.
Redo block break checks to fit above description and the block breaker's own requirements.

**Comment by J-Talon** [comment]
Done.
