### ISSUE TITLE
Config Verification?

### ISSUE THREAD

**Issue by CammHd** [CammHd/Bedwars#7]
Should we implement something to warn users of potential conflicts with the config they supply to the plugin?
If Not, then:
   If the team verifier class is still present, please delete it.
   
If so, then:
  We still might want to delete it to add to organization. We'll make a new class and such instead.

**Comment by J-Talon** [comment]
Thinking about implementing this after refactoring the plugin.
Thought:
   All structures inherit an interface with method String checkValidity()
    which returns null if no problems, and a string of the problem if there is one.
    
    Otherwise, maybe instead have it throw an exception instead of a string, and have the method void?
      -> good for callbacks.

**Comment by al-wen** [comment]
ok
